name: terraform
on:
  push:
    branches: main
    
env:
  ARM_SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.TENANT_ID }}"
  ARM_CLIENT_ID: "${{ secrets.CLIENT_ID }}"
  CONFIG_DIRECTORY: "./"
  ARM_USE_CLI: "false"
  ARM_USE_MSI: "true"
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Log into Azure
        uses: azure/login@v1
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          
      - name: search
        run: ls
        
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: "azure/Manage Azure identities and governance"

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: "azure/Manage Azure identities and governance"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: "azure/Manage Azure identities and governance"

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        working-directory: "azure/Manage Azure identities and governance"

      - name: Apply Terraform changes
        run: terraform apply --auto-approve
        working-directory: "terraform/azure/Manage Azure identities and governance"
